### ISSUE TITLE
Needs a headless mode

### ISSUE THREAD

**Issue by JonnyOThan** [drewcassidy/yaclog#11]
I was trying to use yaclog as part of a github action, but the interactive prompts seem to kill it:

```yml
    - name: update-changelog
      working-directory: ${{ github.workspace }}
      if: ${{ hashFiles( inputs.changelog-input-file ) != '' }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install yaclog yaclog-ksp
        yaclog --path ${{ inputs.changelog-input-file }} release -f ${{ inputs.version-string }}
        yaclog-ksp --path ${{ inputs.changelog-input-file }} -n ${{ github.event.repository.name }} -o ${{ inputs.changelog-output-file }};
        git add ${{ inputs.changelog-output-file }}
```

```
Aborted!
Rename release version 0.2.18.4 to 1.0.0.0? [y/N]: 
Error: Process completed with exit code 1.
```
